- name: Install InfluxDB
  tags:
    - influxdb
    - never
  yum:
    name:
      - influxdb
      - chronograf
    state: present

- name: Copy influxdb templated config and chronograf custom service unit
  tags:
    - influxdb
    - never
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'influxdb.conf.j2', dest: '/etc/influxdb/influxdb.conf' }
    - { src: 'chronograf.service.j2', dest: '/usr/lib/chronograf/scripts/chronograf.service' }
    - { src: 'chronograf.service.j2', dest: '/usr/lib/systemd/system/chronograf.service' }

- name: Start and enable influxdb and chronograf
  tags:
    - influxdb
    - never
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - influxdb
    - chronograf

- name: Copy templated db creation files
  tags:
    - influxdb
    - never
  template:
    src: "{{ item }}.j2"
    dest: "/var/famillegratton.net/ansible/files/v3monitoring/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - influxdbCreateDB.sh
    - createdb.sql

- name: Configure InfluxDB
  tags:
    - influxdb
    - never
  shell: /var/famillegratton.net/ansible/files/v3monitoring/influxdbCreateDB.sh
  args:
    chdir: /var/famillegratton.net/ansible
    creates: /var/famillegratton.net/ansible/deploy/v3monitoring/influxdbCreateDB.deployed
