---

- name: Install pre-requisites (server and clients)
  gather_facts: True
  hosts: all
  tags:
    - prereqs
    - server
    - clients
  roles:
    - v3monitoring/1.prereq

- name: "Server: influxdb, graphite, nginx and grafana"
  gather_facts: True
  hosts: server
  tags:
    - server
    - influxdb
    - graphite
    - nginx
    - grafana
    - never
  roles:
    - v3monitoring/2a.influxdb
    - v3monitoring/2b.graphite
    - v3monitoring/3.grafana

- name: Install telegraf (clients)
  gather_facts: True
  hosts: clients
  tags:
    - clients
    - telegraf
    - never
  roles:
    - v3monitoring/4a.telegraf

- name: Install collectd (clients)
  gather_facts: True
  hosts: clients
  tags:
    - clients
    - collectd
    - never
  roles:
    - v3monitoring/4b.collectd
