- name: Fetch get-pip.py
  tags:
    - graphite
    - never
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /var/famillegratton.net/ansible/files/v3monitoring/get-pip.py
    owner: root
    group: root
    mode: 0755

- name: Install some pre-requisites (git, nginx and libglvnd-glx)
  tags:
    - nginx
    - never
  yum:
    name:
      - git
      - nginx
      - libglvnd-glx.x86_64
    state: present

- name: Create nginx certificates directory
  tags:
    - nginx
    - never
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: 0644
  
- name: Copy and service and config files
  tags:
    - nginx
    - graphite
    - never
  copy:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
     owner: root
     group: root
     mode: 0755
  with_items:
    - { src: 'local_settings.py', dest: '/var/famillegratton.net/ansible/files/v3monitoring/local_settings.py' }
    - { src: 'carbon.service', dest: '/etc/systemd/system/carbon.service' }
    - { src: 'nginx-selfsigned.key', dest: '/etc/nginx/ssl/nginx-selfsigned.key' }
    - { src: 'nginx-selfsigned.crt', dest: '/etc/nginx/ssl/nginx-selfsigned.crt' }
    - { src: 'install_graphite.sh', dest: '/var/famillegratton.net/ansible/files/v3monitoring/install_graphite.sh' }

- name: Copy templated nginx graphite vhost
  tags:
    - nginx
    - graphite
    - never
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'graphite.conf.j2', dest: '/etc/nginx/conf.d/graphite.conf' }
    - { src: 'graphite.service.j2', dest: '/etc/systemd/system/graphite.service' }

- name: Install graphite
  tags:
    - graphite
    - never
  shell: /var/famillegratton.net/ansible/files/v3monitoring/install_graphite.sh
  args:
    chdir: /var/famillegratton.net/ansible
    creates: /var/famillegratton.net/ansible/deploy/v3monitoring/install_graphite.deployed

- name: Start carbon, graphite and nginx
  tags:
    - nginx
    - graphite
    - never
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  with_items:
     - carbon
     - graphite
     - nginx
