//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFG.Comptes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JFG.Comptes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.1.2.0	2012/09/25
        ///	=&gt; RÃ©org du code, CREATE TABLE plus complet.
        ///
        ///v1.1.1.0	2012/09/24
        ///	=&gt; SHOW CREATE TABLE, SHOW TABLES implÃ©mentÃ©es
        ///
        ///v1.1.0.0	2012/09/18
        ///	=&gt; Remplacement du connecteur Devart par MySQL .NET Connector
        ///	=&gt; Ajout du status bar au bas de la fenÃªtre principale
        ///
        ///v1.0.1.0	2012/09/08
        ///	=&gt; Correction du bug de crÃ©ation de bd
        ///
        ///v1.0.0.0	2012/08/23
        ///	=&gt; Version initiale.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comptabilite2 {
            get {
                object obj = ResourceManager.GetObject("comptabilite2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon comptabilite21 {
            get {
                object obj = ResourceManager.GetObject("comptabilite21", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comptabilite3 {
            get {
                object obj = ResourceManager.GetObject("comptabilite3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon comptabilite31 {
            get {
                object obj = ResourceManager.GetObject("comptabilite31", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comptable {
            get {
                object obj = ResourceManager.GetObject("comptable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;DATABASES&gt;
        ///  &lt;Main&gt;
        ///    Host=&quot;oslo&quot; Port=&quot;3306&quot; DB=&quot;comptabilite&quot; ControlUser=&quot;comptes&quot; ControlPassword=&quot;comptes&quot;
        ///    User=&quot;jfg&quot; Password=&quot;jiefg000&quot;
        ///  &lt;/Main&gt;
        ///  &lt;FailOver&gt;
        ///    Host=&quot;comptabilite.famillegratton.net&quot; Port=&quot;3306&quot; DB=&quot;C280972_comptabilite&quot; ControlUser=&quot;C280972_comptes&quot; ControlPassword=&quot;C0mpt3s&quot;
        ///    User=&quot;jfg&quot; Password=&quot;jiefg000&quot;
        ///  &lt;/FailOver&gt;
        ///&lt;/DATABASES&gt;.
        /// </summary>
        internal static string comptes {
            get {
                return ResourceManager.GetString("comptes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jfg {
            get {
                object obj = ResourceManager.GetObject("jfg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vicky1 {
            get {
                object obj = ResourceManager.GetObject("vicky1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vicky2 {
            get {
                object obj = ResourceManager.GetObject("vicky2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
