//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uOne.consoleInfoBV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uOne.consoleInfoBV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecrit par J.F.Gratton, 2011 - 2012.
        /// </summary>
        internal static string about_EcritPar {
            get {
                return ResourceManager.GetString("about_EcritPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.00.00	2012.03.02
        ///	Version initiale.
        /// </summary>
        internal static string CHANGELOG {
            get {
                return ResourceManager.GetString("CHANGELOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consoleInfoBV.
        /// </summary>
        internal static string consoleInfoBV {
            get {
                return ResourceManager.GetString("consoleInfoBV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -about|-version : affiche le changelog.
        /// </summary>
        internal static string help_About {
            get {
                return ResourceManager.GetString("help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -a attribut(s).
        /// </summary>
        internal static string help_Attributs {
            get {
                return ResourceManager.GetString("help_Attributs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -h hostname (default = localhost).
        /// </summary>
        internal static string help_Hostname {
            get {
                return ResourceManager.GetString("help_Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {-m msisdn | -M fichier_de_msisdn}.
        /// </summary>
        internal static string help_MSISDN {
            get {
                return ResourceManager.GetString("help_MSISDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string help_Options {
            get {
                return ResourceManager.GetString("help_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -o fichier_output.
        /// </summary>
        internal static string help_OutputFile {
            get {
                return ResourceManager.GetString("help_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p port (default = 389).
        /// </summary>
        internal static string help_Port {
            get {
                return ResourceManager.GetString("help_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun résultat.
        /// </summary>
        internal static string main_AucunResultat {
            get {
                return ResourceManager.GetString("main_AucunResultat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Exception:.
        /// </summary>
        internal static string main_DirectoryException {
            get {
                return ResourceManager.GetString("main_DirectoryException", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon voicemail_icon {
            get {
                object obj = ResourceManager.GetObject("voicemail_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
