- name: Install collectd (Debian-based)
  tags:
    - collectd
    - never
  apt:
    name:
      - collectd
      - collectd-utils
    state: present
  when: ansible_distribution|lower == 'ubuntu' or ansible_distribution|lower == 'debian'

- name: Install collectd (RH-based)
  tags:
    - collectd
    - never
  package:
    name: collectd
    state: present
  when: ansible_distribution|lower == 'centos' or ansible_distribution|lower == 'fedora'

- name: "Corner-case: Fedora"
  dnf:
    name:
      - collectd-disk
    state: present
  when: ansible_distribution|lower == 'fedora'

- name: Copy configuration template (Debian-based)
  tags:
    - collectd
    - never
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
  when: ansible_distribution|lower =='debian' or ansible_distribution|lower == 'ubuntu'

- name: Copy configuration template (RH-based)
  tags:
    - collectd
    - never
  template:
    src: collectd.conf.j2
    dest: /etc/collectd.conf

- name: Enable and start collectd
  tags:
    - collectd
    - never
  systemd:
    name: collectd
    state: started
    enabled: yes
    daemon_reload: yes
