- name: Install Telegraf
  package:
    name: telegraf
    state: present

- name: Create log file
  file:
    path: /var/log/telegraf.log
    owner: telegraf
    group: telegraf
    mode: 0740
    state: touch

- name: Copy config file
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart telegraf
  systemd:
    name: telegraf
    enabled: true
    state: restarted
