//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFG.Comptes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JFG.Comptes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2013.07.26	v1.2.20
        ///	Retrait du combobox &quot;type d&apos;achat&quot; ; remplacement par un textbox; plus simple à gérer.
        ///
        ///2013.07.24	v1.2.00
        ///	- Ajout de deux nouveaux champs : commentaires &amp; date d&apos;insertion de l&apos;entrée
        ///	- Possibilité de &quot;locker&quot; la BD utilisée pour la session
        ///	- Correction d&apos;une désynchro : la resource string de création de la table basée sur monthly_template
        ///	ne réflétait pas la nouvelle réalité.
        ///
        ///2013.06.29	v1.1.00
        ///	Ajout d&apos;options de connexion
        ///
        ///2013.06.02	v1.00.00
        ///	Version initiale.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon comptabilite2 {
            get {
                object obj = ResourceManager.GetObject("comptabilite2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (mtID int(10) unsigned NOT NULL AUTO_INCREMENT, mtPoste int(10) NOT NULL DEFAULT &apos;0&apos;,
        ///mtDepense decimal(7,2) unsigned NOT NULL, mtPayeur varchar(45) NOT NULL, mtCommentaires varchar(1024) DEFAULT NULL, mtDateInsertion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (mtID), UNIQUE KEY mtID_UNIQUE (mtID), UNIQUE KEY mtPoste_UNIQUE (mtPoste)) ENGINE=InnoDB DEFAULT CHARSET=utf8.
        /// </summary>
        internal static string IDS_SHOWCREATETABLE {
            get {
                return ResourceManager.GetString("IDS_SHOWCREATETABLE", resourceCulture);
            }
        }
    }
}
